name: Publish-Backend

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE-WEBAPP-NAME: bsdis
  AZURE-WEBAPP-PACKAGE-PATH: './server-side/Basketball'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./server-side/Basketball/Basketball.sln

      - name: Build
        run: dotnet build ./server-side/Basketball/Basketball.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./server-side/Basketball/Basketball.sln --configuration Release --no-build

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE-WEBAPP-NAME }}
          publish-profile: '<publishData><publishProfile profileName="bsdis - Web Deploy" publishMethod="MSDeploy" publishUrl="bsdis.scm.azurewebsites.net:443" msdeploySite="bsdis" userName="$bsdis" userPWD="xDgDaaSnC4SH0tpd8wiCWqG4xSvzBEp5qGlzZDsuW1HAf3mf6RYg5KALHkLP" destinationAppUrl="https://bsdis.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="server=bsdi.mysql.database.azure.com; port=3306; database=bsdi; uid=bsdiBakis; pwd=Xu5R4ZYzqyK7HfsTjnLEVr" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases><add name="DefaultConnection" connectionString="server=bsdi.mysql.database.azure.com; port=3306; database=bsdi; uid=bsdiBakis; pwd=Xu5R4ZYzqyK7HfsTjnLEVr" providerName="MySql.Data.MySqlClient" type="MySql" /></databases></publishProfile><publishProfile profileName="bsdis - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-am2-393.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="bsdis\$bsdis" userPWD="xDgDaaSnC4SH0tpd8wiCWqG4xSvzBEp5qGlzZDsuW1HAf3mf6RYg5KALHkLP" destinationAppUrl="https://bsdis.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="server=bsdi.mysql.database.azure.com; port=3306; database=bsdi; uid=bsdiBakis; pwd=Xu5R4ZYzqyK7HfsTjnLEVr" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases><add name="DefaultConnection" connectionString="server=bsdi.mysql.database.azure.com; port=3306; database=bsdi; uid=bsdiBakis; pwd=Xu5R4ZYzqyK7HfsTjnLEVr" providerName="MySql.Data.MySqlClient" type="MySql" /></databases></publishProfile><publishProfile profileName="bsdis - Zip Deploy" publishMethod="ZipDeploy" publishUrl="bsdis.scm.azurewebsites.net:443" userName="$bsdis" userPWD="xDgDaaSnC4SH0tpd8wiCWqG4xSvzBEp5qGlzZDsuW1HAf3mf6RYg5KALHkLP" destinationAppUrl="https://bsdis.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="server=bsdi.mysql.database.azure.com; port=3306; database=bsdi; uid=bsdiBakis; pwd=Xu5R4ZYzqyK7HfsTjnLEVr" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases><add name="DefaultConnection" connectionString="server=bsdi.mysql.database.azure.com; port=3306; database=bsdi; uid=bsdiBakis; pwd=Xu5R4ZYzqyK7HfsTjnLEVr" providerName="MySql.Data.MySqlClient" type="MySql" /></databases></publishProfile></publishData>'
          package: "${{ env.AZURE-WEBAPP-PACKAGE-PATH }}"

